language: c

os: linux
dist: trusty

notifications:
  email:
    on_success: change
    on_failure: always

env:
  matrix:
  - DEFCONFIG_NAME=adi_bcm2709_defconfig ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential bc u-boot-tools gcc-arm-linux-gnueabihf

script:
  - COMMIT_RANGE=$([ "$TRAVIS_PULL_REQUEST" == "false" ] &&  echo "HEAD~1" || echo origin/${TRAVIS_BRANCH}..)
  - make ${DEFCONFIG_NAME}
  - make -j`getconf _NPROCESSORS_ONLN` uImage UIMAGE_LOADADDR=0x8000
  - for file in `ls arch/arm/boot/dts/zynq-*.dts`; do make `basename $file | sed  -e 's\dts\dtb\g'` || exit 1;done
  - scripts/checkpatch.pl --git ${COMMIT_RANGE} --ignore FILE_PATH_CHANGES --ignore LONG_LINE --ignore LONG_LINE_STRING --ignore LONG_LINE_COMMENT
