language: c

branches:
  except:
  - xcomm_zynq
  - adi-4.14.0 # current rebased versions of master; change this when updating kernel ver

os: linux

notifications:
  email:
    on_success: change
    on_failure: always

matrix:
  include:
    - checkpatch: 1
      env: BUILD_TYPE=checkpatch DO_NOT_DOCKERIZE=1
    - env: BUILD_TYPE=dtb_build_test ARCH=arm DTS_FILES=arch/arm/boot/dts/socfpga_*.dts DO_NOT_DOCKERIZE=1
    - env: DEFCONFIG=socfpga_adi_defconfig ARCH=arm IMAGE=zImage
  allow_failures:
    - checkpatch: 1

script:
  - ./ci/travis/run-build-docker.sh
