language: c

branches:
  except:
  - xcomm_zynq
  - adi-4.14.0 # current rebased versions of master; change this when updating kernel ver

os: linux

notifications:
  email:
    on_success: change
    on_failure: always

env:
  matrix:
  - BUILD_TYPE=checkpatch
  - DEFCONFIG=adi_bcm2709_defconfig ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
  - DEFCONFIG=adi_bcm2711_defconfig ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
  - DEFCONFIG=adi_bcmrpi_defconfig ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
  - BUILD_TYPE=compile_test DEFCONFIG=adi_bcm2709_defconfig ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential bc u-boot-tools gcc-arm-linux-gnueabihf

script:
  - ./ci/travis/run-build.sh
