language: c

branches:
  except:
  - xcomm_zynq
  - adi-4.19.0 # current rebased versions of master; change this when updating kernel ver

os: linux

notifications:
  email:
    on_success: change
    on_failure: always

env:
  matrix:
  - BUILD_TYPE=checkpatch DO_NOT_DOCKERIZE=1
  - DEFCONFIG=adi_bcm2709_defconfig ARCH=arm
  - DEFCONFIG=adi_bcm2711_defconfig ARCH=arm
  - DEFCONFIG=adi_bcmrpi_defconfig ARCH=arm

script:
  - ./ci/travis/run-build-docker.sh
