language: c

branches:
  except:
  - xcomm_zynq
  - adi-4.14.0 # current rebased versions of master; change this when updating kernel ver
  - adi-4.19.0

os: linux

notifications:
  email:
    on_success: change
    on_failure: always

env:
  matrix:
  - BUILD_TYPE=checkpatch
  - BUILD_TYPE=dtb_build_test
  - DEFCONFIG_NAME=socfpga_adi_defconfig ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
    DTS_FILES=arch/arm/boot/dts/zynq-*.dts IMAGE=zImage
  - BUILD_TYPE=compile_test
    DEFCONFIG_NAME=socfpga_adi_defconfig ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential bc u-boot-tools gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu

script:
  - ./ci/travis/run-build.sh
